# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: server.proto for package 'pb'

require 'grpc'
require 'server_pb'

module Pb
  module GismeteoWeatherGateway
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'pb.GismeteoWeatherGateway'

      rpc :GetWeather, ::Pb::Empty, ::Pb::Weather
    end

    Stub = Service.rpc_stub_class
  end
end
